const AdLists = [
  {
      id: 1,
      name: "LaserTag",
      imgSrc: "/assets/CSE/lasertag.jpg",
      heading: "Laser Tag",
      desc: "Laser tag is a team-based game simulating combat using infrared guns and sensors. Players navigate arenas, tagging opponents with laser beams while avoiding hits. Without physical projectiles, it's safe for all ages, promoting teamwork, strategy, and combining physical activity with tech-based fun." ,
      regFee: "50/- per person",
      contact: "Arjun KP | 8075551219",
      redirectLink: "/events/cultural/pencildrawing",
  },
  {
    id: 1,
    name: "LaserTag",
    imgSrc: "/assets/CSE/lasertag.jpg",
    heading: "Laser Tag",
    desc: "Laser tag is a team-based game simulating combat using infrared guns and sensors. Players navigate arenas, tagging opponents with laser beams while avoiding hits. Without physical projectiles, it's safe for all ages, promoting teamwork, strategy, and combining physical activity with tech-based fun." ,
    regFee: "50/- per person",
    contact: "Arjun KP | 8075551219",
    redirectLink: "/events/cultural/pencildrawing",
},
{
  id: 1,
  name: "LaserTag",
  imgSrc: "/assets/CSE/lasertag.jpg",
  heading: "Laser Tag",
  desc: "Laser tag is a team-based game simulating combat using infrared guns and sensors. Players navigate arenas, tagging opponents with laser beams while avoiding hits. Without physical projectiles, it's safe for all ages, promoting teamwork, strategy, and combining physical activity with tech-based fun." ,
  regFee: "50/- per person",
  contact: "Arjun KP | 8075551219",
  redirectLink: "/events/cultural/pencildrawing",
},
{
  id: 1,
  name: "LaserTag",
  imgSrc: "/assets/CSE/lasertag.jpg",
  heading: "Laser Tag",
  desc: "Laser tag is a team-based game simulating combat using infrared guns and sensors. Players navigate arenas, tagging opponents with laser beams while avoiding hits. Without physical projectiles, it's safe for all ages, promoting teamwork, strategy, and combining physical activity with tech-based fun." ,
  regFee: "50/- per person",
  contact: "Arjun KP | 8075551219",
  redirectLink: "/events/cultural/pencildrawing",
},
]
export default AdLists;
