const CulturalLists = [
  {
      id: 1,
      name: "LaserTag",
      imgSrc: "/assets/CSE/lasertag.jpg",
      heading: "Laser Tag",
      desc: "Laser tag is a combat simulation using infrared guns.Players navigate arenas,tagging rivals with lasers. Without projectiles,it's safe for all. It promotes teamwork,strategy,and blends physical activity with fun." ,
      regFee: "50/- per person",
      contact: "Arjun KP | 8075551219",
      redirectLink: "/events/cultural/pencildrawing",
  },
  {
    id: 1,
    name: "LaserTag",
    imgSrc: "/assets/CSE/lasertag.jpg",
    heading: "Laser Tag",
    desc: "Laser tag is a combat simulation using infrared guns.Players navigate arenas,tagging rivals with lasers. Without projectiles,it's safe for all. It promotes teamwork,strategy,and blends physical activity with fun." ,
    regFee: "50/- per person",
    contact: "Arjun KP | 8075551219",
    redirectLink: "/events/cultural/pencildrawing",
},
{
  id: 1,
  name: "LaserTag",
  imgSrc: "/assets/CSE/lasertag.jpg",
  heading: "Laser Tag",
  desc: "Laser tag is a combat simulation using infrared guns.Players navigate arenas,tagging rivals with lasers. Without projectiles,it's safe for all. It promotes teamwork,strategy,and blends physical activity with fun." ,
  regFee: "50/- per person",
  contact: "Arjun KP | 8075551219",
  redirectLink: "/events/cultural/pencildrawing",
},
{
  id: 1,
  name: "LaserTag",
  imgSrc: "/assets/CSE/lasertag.jpg",
  heading: "Laser Tag",
  desc: "Laser tag is a combat simulation using infrared guns.Players navigate arenas,tagging rivals with lasers. Without projectiles,it's safe for all. It promotes teamwork,strategy,and blends physical activity with fun." ,
  regFee: "50/- per person",
  contact: "Arjun KP | 8075551219",
  redirectLink: "/events/cultural/pencildrawing",
},
]
export default CulturalLists;
